name: linux-235-cli

on: [push, pull_request]

jobs:
  build-linux-glibc-2-35:
    env:
      ZMQ_VERSION: v4.3.1
      CPPZMQ_VERSION: v4.3.0
      CFLAGS: -fPIC
      CXXFLAGS: -fPIC
      USE_SINGLE_BUILDDIR: 1
      CCACHE_TEMPDIR: /tmp/.ccache-temp
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: ccache-${{ runner.os }}-build-235-${{ github.sha }}
        restore-keys: ccache-${{ runner.os }}-build-235
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";"         | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";"  | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: Install Haven dependencies
      run: |
        sudo apt update
        sudo apt-get --no-install-recommends --yes install build-essential cmake libudev-dev libboost-all-dev miniupnpc graphviz doxygen libunwind8-dev pkg-config libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libnorm-dev libpgm-dev libprotobuf-dev protobuf-compiler ccache
    - name: install unbound-dev
      run: |
        wget https://github.com/libexpat/libexpat/releases/download/R_2_4_1/expat-2.4.1.tar.bz2
        echo "2f9b6a580b94577b150a7d5617ad4643a4301a6616ff459307df3e225bcfbf40 expat-2.4.1.tar.bz2" | sha256sum -c
        tar -xf expat-2.4.1.tar.bz2
        rm expat-2.4.1.tar.bz2
        cd expat-2.4.1
        ./configure --enable-static --disable-shared --prefix=/usr
        make -j3
        sudo make -j3 install

        wget https://www.nlnetlabs.nl/downloads/unbound/unbound-1.13.2.tar.gz
        echo "0a13b547f3b92a026b5ebd0423f54c991e5718037fd9f72445817f6a040e1a83 unbound-1.13.2.tar.gz" | sha256sum -c
        tar -xzf unbound-1.13.2.tar.gz
        rm unbound-1.13.2.tar.gz
        cd unbound-1.13.2
        ./configure --disable-shared --enable-static --without-pyunbound --with-libexpat=/usr --with-ssl=/usr --with-libevent=no --without-pythonmodule --disable-flto --with-pthreads --with-libunbound-only --with-pic
        make -j3
        sudo make -j3 install

        wget https://github.com/libusb/libusb/releases/download/v1.0.26/libusb-1.0.26.tar.bz2
        tar -xf libusb-1.0.26.tar.bz2
        rm libusb-1.0.26.tar.bz2
        cd libusb-1.0.26
        ./configure --disable-shared --enable-static
        make -j3
        sudo make -j3 install

    - name: build Haven
      run: |
        make release-static -j3
    - name: package haven CLI
      run: |
        cd build/release/bin/
        tar -czvf haven-linux-glibc235.tar.gz *
        echo ::set-output name=haven-linux-glibc235::$(sha256sum haven-linux-glibc235.tar.gz)
    - uses: actions/upload-artifact@v2
      with:
        name: haven-linux-glibc235.tar.gz
        path: build/release/bin/haven-linux-glibc235.tar.gz
        retention-days: 10

  upload-linux-glibc-2-35:
    needs: build-linux-glibc-2-35
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: haven-linux-glibc235.tar.gz
    - name: Upload Haven CLI
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: './'
        destination_dir: binaries/${{github.ref_name}}
    - name: notification
      env:
        BINARY_NAME: /haven-linux-glibc235.tar.gz
        BINARY_URL: https://docs.havenprotocol.org/binaries/
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      shell: bash
      run: |
        export checksum=($(sha256sum haven-linux-glibc235.tar.gz))
        export payload='{"username": "Github", "content": "CLI (Linux 2.31) : '${BINARY_URL}${GITHUB_REF_NAME}${BINARY_NAME}' (sha256 checksum : '${checksum}')"}'
        echo $payload
        curl -X POST -H "Content-Type: application/json" -d "$payload" $DISCORD_WEBHOOK

  publish-linux-glibc-2-35:
    needs: build-linux-glibc-2-35
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: haven-linux-glibc235.tar.gz
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: haven-linux-glibc235.tar.gz
        asset_name: haven-linux-glibc235.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
        prerelease: true
