name: winx64-cli

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CCACHE_TEMPDIR: C:\Users\runneradmin\.ccache-temp
      CCACHE_DIR: C:\Users\runneradmin\.ccache
      USE_SINGLE_BUILDDIR: 1
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: actions/cache@v2
      with:
        path: C:\Users\runneradmin\.ccache
        key: ccache-${{ runner.os }}-build-${{ github.sha }}
        restore-keys: ccache-${{ runner.os }}-build-
    - uses: eine/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-ccache mingw-w64-x86_64-boost mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-protobuf-c mingw-w64-x86_64-libusb mingw-w64-x86_64-unbound git
    - name: build
      run: |
        ccache --max-size=150M
        ccache --set-config=compression=true
        make release-static-win64 -j2
    - name: package haven CLI
      run: |
        cd build/release/bin/
        tar -czvf haven-windows.tar.gz *.exe
        echo ::set-output name=haven-windows::$(sha256sum haven-windows.tar.gz)
    - uses: actions/upload-artifact@v2
      with:
        name: haven-windows.tar.gz
        path: build/release/bin/haven-windows.tar.gz
        retention-days: 10

  upload-windows:
    needs: build-windows
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: haven-windows.tar.gz
    - name: Upload Haven CLI
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        source_dir: './'
        destination_dir: binaries/${{github.ref_name}}
    - name: notification
      env:
        BINARY_NAME: /haven-windows.tar.gz
        BINARY_URL: https://docs.havenprotocol.org/binaries/
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      shell: bash
      run: |
        export checksum=($(sha256sum haven-windows.tar.gz))
        export payload='{"username": "Github", "content": "CLI (Windows) : '${BINARY_URL}${GITHUB_REF_NAME}${BINARY_NAME}' (sha256 checksum : '${checksum}')"}'
        echo $payload
        curl -X POST -H "Content-Type: application/json" -d "$payload" $DISCORD_WEBHOOK

  publish-windows:
    needs: build-windows
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: haven-windows.tar.gz
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: haven-windows.tar.gz
        asset_name: haven-windows.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
        prerelease: true